version: '3.1'
networks:
  app-tier:
    driver: bridge
services:
  app:
    container_name: docker-springboot-postgresql
    image: docker-springboot-postgresql
    build: ./
    ports:
      - "8080:8020"
    depends_on:
      - postgresqldb
      - redis
  postgresqldb:
    image: postgres
    ports:
      - "6534:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rigdb
  redis:
    image: 'bitnami/redis:latest'
    container_name: 'redis-cache'
    environment:
      - REDIS_PASSWORD=beril123
    labels:
      kompose.service.type: nodeport
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis'
    networks:
        - app-tier
volumes:
  redis_data:
    driver: local