server:
  port: 8020

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:6534/rigdb
    username: postgres
    password: postgres
    maximum-pool-size: 3
    minimum-idle: 3
redis:
  port: 6379
  host: localhost
  password: beril123
general:
  cache:
    denemeCountsInSeconds: 2
springdoc:
  packagesToScan: com.demo.readingisgood
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}
    path: /swagger-ui
